# -*- coding: utf-8 -*-
"""
user_simulator_agent — main entry point
========================================
读取 user_profile，自动完成：
  1. 解析用户画像
  2. 设计电脑环境规格（目录结构 + 文件列表 + env_config）
  3. 生成 / 下载所有文件
  4. 输出 env_config.json
  5. 生成 user_agent.py

核心 API：
  run_pipeline(user_profile_path, output_dir, profile_dir_name=None)
"""

import os, sys, json, time
from pathlib import Path
from datetime import datetime

# Windows GBK 控制台兼容：强制 stdout/stderr 使用 UTF-8
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# ─── 路径设置 ──────────────────────────────────────────────────────────────────
_WORKING_SPACE = Path(__file__).resolve().parent         # WorkingSpace/
_PROJECT_ROOT  = _WORKING_SPACE.parent                    # user_simulator_agent/

# 把 WorkingSpace 和 project root 都加到 sys.path，保证 utils.* / agents.* / config.* / shared.* 都能导入
if str(_WORKING_SPACE) not in sys.path:
    sys.path.insert(0, str(_WORKING_SPACE))
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from config.config_loader import load_config


# ── helpers ────────────────────────────────────────────────────────────────────
def _banner(msg: str) -> None:
    print("\n" + "═" * 60)
    print(f"  {msg}")
    print("═" * 60)



def _sanitize_name(name: str) -> str:
    """移除 Windows 目录名中不允许的字符。"""
    for ch in r'\/:*?"<>|':
        name = name.replace(ch, "_")
    return name.strip()


def _build_readme(profile: dict, spec: dict, created: list) -> str:
    lines = [
        f"# 模拟电脑环境 — {profile.get('name')}（{profile.get('role')}）",
        "",
        f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**操作系统**: {profile.get('os')}",
        f"**单位**: {profile.get('company')} · {profile.get('department')}",
        "",
        "## 目录结构",
        "```",
        *[f"  {d}" for d in spec.get("directories", [])],
        "```",
        "",
        "## 文件清单",
        "",
    ]
    for f in spec.get("files", []):
        tag = "🌐" if f.get("type") == "downloadable" else "📝"
        lines.append(f"- {tag} `{f['path']}` — {f.get('description','')}")
    lines += [
        "",
        "## 任务",
        "",
        profile.get("task_description", ""),
        "",
        "---",
        "*Generated by user_simulator_agent*",
    ]
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
#  核心 pipeline（可从外部 import 调用）
# ══════════════════════════════════════════════════════════════════════════════
def run_pipeline(
    user_profile_path: Path | str,
    output_dir: Path | str,
    profile_dir_name: str | None = None,
    query: str | None = None,
) -> dict:
    """
    执行完整的 4 步 pipeline。

    Args:
        user_profile_path:  用户画像文件（txt 或 json），绝对路径
        output_dir:         输出根目录（绝对路径）
        profile_dir_name:   生成的文件系统子目录名。
                            为 None 时自动从分析结果推导（"姓名_职业"）。

    Returns:
        dict  包含 profile_name、profile、created_files、output_dir 等
    """
    t0 = time.time()
    _banner("user_simulator_agent 启动")

    # ── 导入子模块 ──────────────────────────────────────────────────────────
    from utils.llm_client            import LLMClient
    from utils.web_tools             import WebTools
    from agents.profile_analyzer     import ProfileAnalyzer
    from agents.computer_spec_designer import ComputerSpecDesigner
    from agents.file_processor       import FileProcessor

    # ── 读取配置 ──────────────────────────────────────────────────────────
    cfg      = load_config()
    api_cfg  = cfg.get("api_config", {})
    web_cfg  = cfg.get("web_tools_config", {})
    pipe_cfg = cfg.get("pipeline_config", {})

    llm_api_key  = os.getenv("LLM_API_KEY",  api_cfg.get("LLM_API_KEY", ""))
    llm_base_url = os.getenv("LLM_BASE_URL", api_cfg.get("LLM_BASE_URL", ""))
    llm_model    = os.getenv("LLM_MODEL",    api_cfg.get("LLM_MODEL", "gpt-4o"))
    llm_backend  = os.getenv("LLM_BACKEND",  api_cfg.get("LLM_BACKEND", "openai"))
    serper_key   = os.getenv("SERPER_KEY",    web_cfg.get("SERPER_KEY", ""))
    jina_key     = os.getenv("JINA_KEY",      web_cfg.get("JINA_KEY", ""))
    max_workers  = int(os.getenv("MAX_WORKERS", str(pipe_cfg.get("MAX_WORKERS", 8))))

    # ── 初始化工具 ──────────────────────────────────────────────────────────
    llm = LLMClient(llm_api_key, llm_base_url, llm_model, backend=llm_backend)
    web = WebTools(serper_key, jina_key)

    # ── 读取用户画像 ────────────────────────────────────────────────────────
    user_profile_path = Path(user_profile_path)
    if not user_profile_path.exists():
        sys.exit(f"[Error] 找不到 {user_profile_path}")
    profile_text = user_profile_path.read_text(encoding="utf-8")
    print(f"\n[读取] {user_profile_path} ({len(profile_text)} chars)")

    # ── Step 1：分析用户画像 ────────────────────────────────────────────────
    _banner("Step 1 / 3  分析用户画像")
    analyzer = ProfileAnalyzer(llm)
    profile  = analyzer.analyze(profile_text)

    # ── 确定 profile 目录名（替代原来的 "computer_profile"） ────────────────
    if not profile_dir_name:
        profile_dir_name = _sanitize_name(
            f"{profile.get('name', 'user')}_{profile.get('role', 'unknown')}"
        )

    # ── 创建输出目录 ────────────────────────────────────────────────────────
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Query 注入（可选）──────────────────────────────────────────────────
    if query:
        print(f"\n  [Query 模式] 注入 query: {query[:80]}...")
        original_task = profile.get("task_description", "")
        original_ctx  = profile.get("task_context", "")
        profile["task_description"] = (
            f'用户当前收到一个具体请求："{query}"。'
            f'需要确保文件系统中真实存在能支撑该请求的相关文件。'
            f'原始工作背景：{original_task}'
        )
        profile["task_context"] = (
            f'该请求要求文件系统中存在可直接使用的文件。'
            f'原始上下文：{original_ctx}'
        )
        profile["user_query"] = query

    # 持久化 Step 1 结果，供后续断点续跑使用
    (out_dir / "profile_analyzed.json").write_text(
        json.dumps(profile, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # ── Step 2：设计电脑环境规格 ────────────────────────────────────────────
    _banner("Step 2 / 3  设计电脑环境")
    designer = ComputerSpecDesigner(llm)
    spec     = designer.design(profile)

    # 持久化 Step 2 结果，供后续断点续跑使用
    (out_dir / "spec.json").write_text(
        json.dumps(spec, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    profile_dir = out_dir / profile_dir_name
    profile_dir.mkdir(exist_ok=True)

    # ── Step 3：生成文件系统 ─────────────────────────────────────────────────
    _banner("Step 3 / 3  生成文件 & 目录")
    processor = FileProcessor(llm, web, str(out_dir), max_workers=max_workers)
    created   = processor.process(spec, profile, profile_dir_name=profile_dir_name)

    # ── 写入 env_config.json ─────────────────────────────────────────────────
    env_cfg = spec.get("env_config", {})
    env_path = profile_dir / "env_config.json"
    env_path.write_text(
        json.dumps(env_cfg, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"\n  → env_config.json 已写入")

    # ── 写入 README ──────────────────────────────────────────────────────────
    readme = _build_readme(profile, spec, created)
    (profile_dir / "README.md").write_text(readme, encoding="utf-8")

    # ── 写入 pipeline_meta.json（记录来源画像路径，供 query_generate.py 使用） ──
    pipeline_meta = {
        "source_profile_path": str(user_profile_path.resolve()),
        "env_dir": str(out_dir.resolve()),
        "profile_dir_name": profile_dir_name,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "query": query,
    }
    (out_dir / "pipeline_meta.json").write_text(
        json.dumps(pipeline_meta, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"\n  → pipeline_meta.json 已写入")

    # ── 完成汇总 ─────────────────────────────────────────────────────────────
    elapsed = time.time() - t0
    _banner("完成 [OK]")
    print(f"\n  模拟角色    : {profile.get('name')}（{profile.get('role')}）")
    print(f"  创建文件数  : {len(created)}")
    print(f"  耗时        : {elapsed:.1f} 秒\n")
    print(f"  📁 输出目录 : {out_dir}")
    print()

    # ── 标记任务完成 ───────────────────────────────────────────────────────
    (out_dir / "task_done.txt").write_text("", encoding="utf-8")

    return {
        "profile_dir_name": profile_dir_name,
        "profile": profile,
        "created_files": created,
        "output_dir": str(out_dir),
    }


# ══════════════════════════════════════════════════════════════════════════════
#  独立运行入口
# ══════════════════════════════════════════════════════════════════════════════
def main() -> None:
    cfg      = load_config()
    pipe_cfg = cfg.get("pipeline_config", {})

    user_profile_path = Path(
        os.getenv("USER_PROFILE_PATH", pipe_cfg.get("USER_PROFILE_PATH", "user_profile.txt"))
    )
    output_dir = Path(
        os.getenv("OUTPUT_DIR", pipe_cfg.get("OUTPUT_DIR", "output"))
    )

    # 独立运行时，相对路径基于 WorkingSpace/
    if not user_profile_path.is_absolute():
        user_profile_path = _WORKING_SPACE / user_profile_path
    if not output_dir.is_absolute():
        output_dir = _WORKING_SPACE / output_dir

    run_pipeline(user_profile_path, output_dir)


if __name__ == "__main__":
    main()
